export const GET_DOGS = "GET_DOGS";
export const FILTER_DOGS_BY_TEMPERAMENT = "FILTER_DOGS_BY_TEMPERAMENT";
export const GET_DOGS_BY_NAME = "GET_DOGS_BY_NAME ";
export const GET_TEMPERAMENTS = "GET_TEMPERAMENTS";
export const ORDER_BY_NAME = "ORDER_BY_NAME";
